### ISSUE TITLE
auto=format/compress parity with Imgix (webp, fallbacks, etc)

### ISSUE THREAD

**Issue by timkelty** [venveo/serverless-sharp#12]
Ideally our `auto=format` would work as outlined here: https://docs.imgix.com/tutorials/improved-compression-auto-content-negotiation

Specifically how it interacts with:

- q
- fm
- lossless
- auto=compress

Examples:

non-transparent png, converted to jpeg (because of auto=compress):

```
curl -Is --header "Accept: image/webp" "https://sandbox-uploads.imgix.net/u/1564500457-81c86edec482b1990cde976607152d31?auto=compress" | grep "content-type:"
content-type: image/jpeg
```

png w/ transparency, remaining png (despite of auto=compress, because it has transparency):

```
curl -Is "https://static.imgix.net/feature-retina.png?auto=compress" | grep "content-type:"
content-type: image/png
```

In either case, will be served as a webp with `auto=format` included, and requested from a webp browser:

```
curl -Is --header "Accept: image/webp" "https://static.imgix.net/feature-retina.png?auto=compress,format" | grep "content-type:"
content-type: image/webp
```

**Comment by Mosnar** [comment]
This is done
