### ISSUE TITLE
Configure quality defaults in env

### ISSUE THREAD

**Issue by timkelty** [venveo/serverless-sharp#13]
Something like…

- `DEFAULT_QUALITY=75` https://docs.imgix.com/apis/url/format/q
- `DEFAULT_COMPRESS_QUALITY=45` https://docs.imgix.com/apis/url/auto/auto#compress

**Comment by Mosnar** [comment]
- [ ] DEFAULT_QUALITY
- [ ] DEFAULT_COMPRESS_QUALITY
- [ ] MAX_OUTPUT_HEIGHT
- [ ] MAX_OUTPUT_WIDTH
