### ISSUE TITLE
FYI possible PRs next week

### ISSUE THREAD

**Issue by eboto** [venveo/serverless-sharp#35]
Hi! I see that the project is under active development so I just want to give a heads-up that I have a pending branch implementing `fm=json`, `rect=`, and reverse-proxy image origins (as opposed to S3 buckets). I'm building this for a client so I can't guarantee that they will agree to open source the extensions, but I am recommending that we do and I think it is fairly likely.

Just giving this heads-up, so that you don't choose to duplicate my extensions until we know whether I will be able to contribute them =)

**Comment by Mosnar** [comment]
Great! Looking forward to it! At least a few people, myself included, are using this project in production, so you can rest assured it will not be abandoned (until a better drop-in replacement exists)
