### ISSUE TITLE
SLS ignore usage

### ISSUE THREAD

**Issue by gregBerthelot** [venveo/serverless-sharp#44]
Hi @Mosnar we have deployed serverless sharp and serve cloudfront/siteID/images/some-image.jpg successfully

In the meantime we already serve cloudfront/siteID/css/theme.min.css from the same distri and we get an internal server error. How can we ignore css files? Should it be at the API level or with SLS ignore?

Thanks
Greg

**Comment by gregBerthelot** [comment]
Fixed it by using multiple origins on Cloudfront with dedicated behavior for each file type eg:
- *.jpg from API Gateway
- *.css from S3 Bucket

**Comment by Mosnar** [comment]
Nice!
