### ISSUE TITLE
Custom alias / domain + domain certificate for Cloudfront Distribution

### ISSUE THREAD

**Issue by bs-thomas** [venveo/serverless-sharp#47]
Is this not yet supported at the moment? 

If not, I'm interested in seeing if I can spend some time to add this option to the stack.  Would be nice to have beautiful domains for image CDNs I was thinking ;-)

**Comment by bs-thomas** [comment]
https://github.com/venveo/serverless-sharp/pull/48

**Comment by Mosnar** [comment]
Thanks again! Added for next release!

**Comment by bs-thomas** [comment]
@Mosnar np.  :-) Please note that when custom domain is used, the region will have to be us-east-1 because that is the only way certificates can be made automatically (cloudfront certificates will have to be us-east-1 in order to be binded).

**Comment by Mosnar** [comment]
@bs-thomas Good catch! I'm working on refactoring the docs, so I'll be sure to include a note of that.
