### ISSUE TITLE
Any reason why nodejs10.x is used instead of nodejs12.x

### ISSUE THREAD

**Issue by bs-thomas** [venveo/serverless-sharp#59]
As per the topic, I'm wondering why we're using nodejs10.x instead of nodejs12.x.  Is there any reason for that?

Thanks!

**Comment by Mosnar** [comment]
I believe it was inherited from the original AWS implementation of Lambda + Sharp. Let's get that up to date!

**Comment by Mosnar** [comment]
Updated NodeJS as well as Sharp. Next tagged will release will use nodejs12.x!
