### ISSUE TITLE
Latest released v2.0.3 as-is, I'm getting this.

### ISSUE THREAD

**Issue by bs-thomas** [venveo/serverless-sharp#63]
Seems like there are issues with the sharp libraries.

```
2020-05-04T16:48:05.710Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "\nSomething went wrong installing the \"sharp\" module\n\n/opt/nodejs/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: file too short\n\n- Remove the \"node_modules/sharp\" directory then run\n  \"npm install --ignore-scripts=false --verbose\" and look for errors\n- Consult the installation documentation at https://sharp.pixelplumbing.com/install\n- Search for this error at https://github.com/lovell/sharp/issues\n",
    "stack": [
        "Error: ",
        "Something went wrong installing the \"sharp\" module",
        "",
        "/opt/nodejs/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: file too short",
        "",
        "- Remove the \"node_modules/sharp\" directory then run",
        "  \"npm install --ignore-scripts=false --verbose\" and look for errors",
        "- Consult the installation documentation at https://sharp.pixelplumbing.com/install",
        "- Search for this error at https://github.com/lovell/sharp/issues",
        "",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/lib/constructor.js:34:9)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1044:19)",
        "    at require (internal/modules/cjs/helpers.js:77:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/lib/index.js:3:15)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)"
    ]
}
```

**Comment by Mosnar** [comment]
Hmm, strange. Worked while I was testing it. Will figure it out today.

**Comment by bs-thomas** [comment]
That should explain it.  I still haven't tested it, but already excited after getting my downloaded copy, and sls deploying this!

![image](https://user-images.githubusercontent.com/2464920/80992738-8c51ba80-8e6c-11ea-8b45-cee023c73b77.png)

**Comment by bs-thomas** [comment]
@Mosnar  And it works...

**Comment by bs-thomas** [comment]
By the way, on the side note (somewhat related)...

**Are these supposed to be changed from:**
lambdaLayers/SharpLayer/lib/libvips.so.42.11.0
lambdaLayers/SharpLayer/lib/libvips-cpp.so.42.11.0

**to:**
lambdaLayers/SharpLayer/lib/libvips.so.42.12.1
lambdaLayers/SharpLayer/lib/libvips-cpp.so.42.12.1

?

**Comment by bs-thomas** [comment]
@Mosnar Sorry for spamming... but it seems to me that even if the folder "lambdaLayers/SharpLayer/lib/" is missing, it still works.  Is that an outdated useless folder?

**Comment by Mosnar** [comment]
@bs-thomas Yeah, that's what I'm looking into now. I think I may have been a little overzealous with updating without reading the full changelog. To be honest, I don't have a perfect understanding of how this part of the project works.

It looks like this was a significant change that may be working in our favor: https://github.com/lovell/sharp/issues/1282

**Comment by Mosnar** [comment]
@bs-thomas Ahah! It looks like when I built the original binaries, they were symlinked - which is what caused them to be empty.

**Comment by Mosnar** [comment]
Found another issue with the latest version of Serverless not properly excluding dev dependencies anymore. Patching that and then I'll make another release once I've done an end-to-end test. 


As always, thank you again for all the help @bs-thomas !
