### ISSUE TITLE
findBin always results in true

### ISSUE THREAD

**Issue by mattgrayisok** [venveo/serverless-sharp#76]
**Describe the bug**
In ImageHandler.js `findBin` always returns a string but is subsequently used in an if() to determine whether or not to execute the binary. As it's a string it'll always be true even if the file doesn't exist.

**To Reproduce**
1. Look at source code for ImageHandler.js
2. See bug

**Expected behavior**
findBin should probably return false if the file doesn't exist

**Additional context**
I'm playing with this to get it running on GCP Functions so please excuse my deep perusal of your source ;)

**Comment by Mosnar** [comment]
@mattgrayisok Thanks for reporting! I think that's some legacy cruft. Will take care of it during our next sprint. If you get it running on GCP and want to share your findings, feel free to hit me up on Discord! Would love to actually generalize this project and make real use of the Serverless advantage at some point.

**Comment by Mosnar** [comment]
Closed this issue since we now use the built in PNG quantization of Sharp.
