### ISSUE TITLE
[Question] When using "auto=format", should SVGs also be excluded from returning as webp?

### ISSUE THREAD

**Issue by kylecotter** [venveo/serverless-sharp#88]
When setting the format to auto, is it within reason to also ignore SVGs as you do Gifs?

Currently it's just set to ignore gifs.

```
if (fm !== 'gif' && headers.Accept.indexOf('image/webp') !== -1) {
    fm = 'webp'
}
```

from here https://github.com/venveo/serverless-sharp/blob/master/src/ImageHandler.js#L142

My context is I'm using this inside the Craft CP and for svg icons in assets some return pixelated in the webp format. Returning the actual svg would solve that.

Let me know if that's something that would be acceptable and can make a PR for it.

Thanks!

**Comment by Mosnar** [comment]
Yeah, definitely. PR would always be appreciated! :)
